<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NastiaPC" name="com.example.tests.ContactCreationTests" tests="2" failures="0" timestamp="17 Feb 2015 07:30:15 GMT" time="10.496" errors="1">
  <testcase name="testValidContactCanBeCreated" time="2.806" classname="com.example.tests.ContactCreationTests"/>
  <testcase name="testUiAndDbConformsWithModel" time="7.690" classname="com.example.tests.ContactCreationTests">
    <error type="java.lang.AssertionError" message="
Expected: &lt;Contacts [storedConacts=[Contact [43: Name1029314288, Email1968849739], Contact [44: Name1029314288, Email1968849739], Contact [45: Name1029314288, Email1968849739]]]&gt;
     but: was &lt;Contacts [storedConacts=[Contact [43: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795], Contact [44: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795], Contact [45: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795]]]&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <Contacts [storedConacts=[Contact [43: Name1029314288, Email1968849739], Contact [44: Name1029314288, Email1968849739], Contact [45: Name1029314288, Email1968849739]]]]]><![CDATA[>
     but: was <Contacts [storedConacts=[Contact [43: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795], Contact [44: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795], Contact [45: Name1029314288 LastName-1500215359, Email1968849739;Email21205235795]]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.example.tests.ContactCreationTests.testUiAndDbConformsWithModel(ContactCreationTests.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testUiAndDbConformsWithModel -->
</testsuite> <!-- com.example.tests.ContactCreationTests -->
